### ISSUE TITLE
Windows tortoiseSVN update to revision fails

### ISSUE THREAD

**Issue by GuillaumeBibaut** [m-hall/HypnotoadSVN#20]
https://github.com/m-hall/HypnotoadSVN/blob/b0b72b891e4986683c48f52ed85ccf82708aace1/svn_commands.py#L312

It seems that the `files` variable isn't instanced at this point. Maybe moving lines 316 and 317 before line 311 would bring a sufficient fix ?

Here is the debug I'm getting in Sublime Text 3:
```
HypnotoadSVN: Update to revision
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "svn_commands in C:\Users\Guillaume\AppData\Roaming\Sublime Text 3\Installed Packages\HypnotoadSVN.sublime-package", line 312, in run
UnboundLocalError: local variable 'files' referenced before assignment
```

**Comment by m-hall** [comment]
Thanks for the fix!
